// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Fomar0153_TileSize","status":true,"description":"Allows you to use tiles of a different size in game.","parameters":{"Tile Size":"32","Key String":"!"}},
{"name":"yanflycoreengine","status":false,"description":"","parameters":{}}
];
