// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Fomar0153_TileSize","status":true,"description":"Allows you to use tiles of a different size in game.","parameters":{"Tile Size":"32","Key String":"!"}},
{"name":"yanflycoreengine","status":false,"description":"","parameters":{}},
{"name":"Zoom","status":true,"description":"v0.6.0 Map zoom","parameters":{"Default zoom for maps":"1.50","Always free camera":"false","Fix sprite black lines":"true","Fix map encounter zoom":"true"}},
{"name":"Theo_EnemyHPGauge","status":true,"description":"v1.0.1 - Theo Enemy HP Gauge | Visual HP gauge for the enemies","parameters":{"option":"","pos":"Top","defeat":"false","alwaysShown":"false","prop":"","width":"100","height":"11","animeDur":"45","displayDur":"25","border":"2","segments":"1","gaugecolor":"","lcolorindex":"20","rcolorindex":"21","bcolorindex":"15","aftImage":"18","aftAlpha":"200"}},
{"name":"destinationsprite","status":true,"description":"v1.0.1 Customize the destination sprite","parameters":{"type":"invisible","xOffset":"0","yOffset":"0","color":"#ffffff","outlineColor":"","blendMode":"1","scale":"1.00","animation":"{\"bounceRate\":\"20\",\"minOpacity\":\"16\",\"maxOpacity\":\"192\",\"minScale\":\"0.15\",\"maxScale\":\"1.50\"}"}}
];
